
name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  frontend-build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install and Build
      working-directory: frontend
      run: |
        npm install
        npm run build
    - name: Docker Build and Push
      run: |
        docker build -t 17rj/three-tier-todo-frontend  frontend/
        echo  ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push 17rj/three-tier-todo-frontend:latest
