

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  frontend-build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install and Build
      working-directory: frontend
      run: |
        npm install
        npm run build
