# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  frontend-build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Install and Build
      working-directory: frontend
      run: |
        npm install
        npm run build
